[providers.node]
nodeVersion = "20"

[phases.setup]
nixPkgs = ["nss", "nspr", "atk", "atspi", "libdrm", "libxcb", "libXext", "libXcomposite", "libXdamage", "libXrandr", "mesa", "pango", "cairo", "alsa-lib", "glib"]
